package minesweeper

fun main() {
    val field = """
        .X.......
        .....X..X
        ....X....
        ......X..
        ..X......
        ....X....
        ..X......
        ..X......
        ......X..
    """.trimIndent()

    println(field)
}
